# Generated by Django 3.2 on 2021-04-13 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('payment', models.IntegerField(default=100000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('public', models.BooleanField(default=False)),
                ('client', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('payment', models.IntegerField(default=100000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('public', models.BooleanField(default=False)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(max_length=80)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('1', 'Открыта'), ('2', 'В работе'), ('3', 'Закрыта')], default=1, max_length=7)),
                ('priority', models.CharField(choices=[('1', 'Низкий'), ('2', 'Ниже среднего'), ('3', 'Средний'), ('4', 'Выше среднего'), ('5', 'Высокий'), ('6', 'Реального времени')], default=3, max_length=10)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(null=True)),
            ],
            options={
                'ordering': ['end_date', 'task_name'],
            },
        ),
    ]
