# Generated by Django 3.2 on 2021-04-20 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assign',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
