# Generated by Django 3.2 on 2021-04-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_taskmodel_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={},
        ),
    ]
