# Generated by Django 3.2 on 2021-04-13 14:42

import companies.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('phone_num_1', models.CharField(max_length=12, validators=[companies.validators.phone_num_validator])),
                ('phone_num_2', models.CharField(blank=True, max_length=12, null=True, validators=[companies.validators.phone_num_validator])),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('addr', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('phone_num_1', models.CharField(max_length=12, validators=[companies.validators.phone_num_validator])),
                ('phone_num_2', models.CharField(blank=True, max_length=12, null=True, validators=[companies.validators.phone_num_validator])),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_c_name_2d8260_idx'),
        ),
    ]
